src/x11deb add both x64,arm64
src/Dockerfile.x11deb open x64

diff --git a/src/Dockerfile.x11deb b/src/Dockerfile.x11deb
--- a/src/Dockerfile.x11deb
+++ b/src/Dockerfile.x11deb
@@ -36,6 +36,54 @@ RUN \
 #   dpkg -l |grep asbru && exit 0 || exit 1; 
 
 
+##########
+
+#install base pkg
+RUN apt-get update && \
+apt-get install wget  systemctl nano vim  curl gnupg  ca-certificates -y
+
+# #arm64: use jiangcuo_proxmox_arm64 https://github.com/jiangcuo/Proxmox-Arm64
+# RUN echo "deb https://mirrors.apqa.cn/proxmox/ pvearm  main">/etc/apt/sources.list.d/foxi.list && \
+# curl -L https://mirrors.apqa.cn/proxmox/gpg.key |apt-key add -
+#x64: add proxmox repo
+RUN echo "deb http://mirrors.ustc.edu.cn/proxmox/debian/ bullseye pve-no-subscription" >>/etc/apt/sources.list && \
+curl https://mirrors.ustc.edu.cn/proxmox/debian/proxmox-release-bullseye.gpg|apt-key add -
+
+#intall proxmox-ve without recommends. ##x64:ifupdown2 will install failed but ok
+RUN apt-get update && \
+DEBIAN_FRONTEND=noninteractiv apt-get -y --no-install-recommends  install  proxmox-ve || echo ok
+
+# x64 only
+  #repacked proxmox-ve
+  RUN wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/proxmox-ve_7.2-1_all.deb && \
+  mkdir /tmp/pve && \
+  dpkg -X proxmox-ve_7.2-1_all.deb /tmp/pve/ && \
+  dpkg -e proxmox-ve_7.2-1_all.deb /tmp/pve/DEBIAN && \
+  sed -i "s/pve-kernel-helper,//g" /tmp/pve/DEBIAN/control && \
+  sed -i "s/pve-kernel-5.15,//g" /tmp/pve/DEBIAN/control && \
+  dpkg-deb -Zxz  -b /tmp/pve/ /tmp/
+
+  #repacked pve-manager
+  RUN wget https://mirrors.ustc.edu.cn/proxmox/debian/dists/bullseye/pve-no-subscription/binary-amd64/pve-manager_7.2-7_amd64.deb && \
+  mkdir /tmp/pve-manager && \
+  dpkg -X pve-manager_7.2-7_amd64.deb  /tmp/pve-manager/ && \
+  dpkg -e pve-manager_7.2-7_amd64.deb /tmp/pve-manager/DEBIAN && \
+  sed -i "s/ifupdown2 (>= 2.0.1-1+pve8) | ifenslave (>= 2.6),//g" /tmp/pve-manager/DEBIAN/control && \
+  dpkg-deb -Zxz  -b /tmp/pve-manager/ /tmp
+
+  ##install again
+  RUN dpkg -i /tmp/*.deb || echo ok
+
+#set passwd for root
+RUN echo "root:root"|chpasswd
+
+#clean
+RUN rm -rf /var/lib/apt/lists/*  /*.deb
+
+#use setup.sh to start proxmox service
+STOPSIGNAL SIGINT
+CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target"]
+
 
 ENV \
   TERM=xterm \
